import json
from pathlib import Path

import pandas as pd
import streamlit as st

from app._bootstrap import bootstrap
bootstrap()
from app.security_ui import security_context, security_registry
from app.ui import configure_page, footer, page_header, section, status_pills
from backend.config import SETTINGS

configure_page("Security center", "🔐")
context = security_context("security:read")
page_header("Security center", "Manage access and verify the trust boundary.", "Inspect scoped keys, members, quarantined uploads, and the tamper-evident audit chain for this organization.")

if SETTINGS.platform_mode == "postgres":
    from app.production_ui import render_security
    render_security()
    st.stop()

registry = security_registry()
chain = registry.verify_audit_chain()
quarantine = registry.list_quarantine(context)
status_pills([("Tenant isolated", True), ("Audit chain valid", chain["valid"]), (f"{len(quarantine)} quarantine cases", not quarantine)])

gate_path = Path("outputs/security/security_gate.json")
if gate_path.exists():
    gate = json.loads(gate_path.read_text("utf-8"))
    section("Adversarial RAG result", "The retained result is generated by the security validation runner.")
    st.metric("Decision", gate["decision"].upper())
    st.caption(f"{gate['case_count']} cases · " + ", ".join(f"{name}: {count}" for name, count in gate["category_counts"].items()))
    failed = [name for name, passed in gate["gates"].items() if not passed]
    if failed:
        st.warning("Open gates: " + ", ".join(failed))

section("API keys", "Secrets are displayed only once when created; this table contains identifiers and status only.")
st.dataframe(pd.DataFrame(registry.list_api_keys(context)), use_container_width=True, hide_index=True)

if context.role == "owner":
    section("Members", "Role permissions are deny-by-default, and key scopes can only reduce them.")
    st.dataframe(pd.DataFrame(registry.list_members(context)), use_container_width=True, hide_index=True)

section("Quarantine", "High-risk uploads remain outside the active vector and lexical indexes until reviewed.")
st.dataframe(pd.DataFrame(quarantine), use_container_width=True, hide_index=True)

section("Audit verification", "Every event is linked to the previous event with an HMAC hash.")
st.json(chain)
if st.download_button("Export redacted audit JSONL", data="\n".join(json.dumps(row, sort_keys=True) for row in reversed(registry.list_audit(context, 1000))), file_name="audit-redacted.jsonl", mime="application/x-ndjson"):
    registry.append_audit(context.organization_id, context.user_id, context.key_id, "audit.export", "audit", None, "success", 200)
footer()
